### ISSUE TITLE
[프론트엔드 배포 정보]

### ISSUE THREAD

**Issue by Moorisong** [WillNeiman/MongBit_Backend#1]
## 백엔드와 테스트 시 참고하세요. @WillNeiman 

- 경로
  - https://mong-bit-frontend.vercel.app
 
- 페이지
  - [x] /main
  - [x] /test-list
  - [x] /test

- 프론트엔드 리포지토리
- https://github.com/Moorisong/MongBit_Frontend/issues/5

**Comment by WillNeiman** [comment]
확인했습니다
