### ISSUE TITLE
[백엔드 배포 정보]

### ISSUE THREAD

**Issue by WillNeiman** [WillNeiman/MongBit_Backend#2]
### 경로
  - https://mongbit-willneiman.koyeb.app/

### 개발 서버 API 명세서
 - https://mongbit-willneiman.koyeb.app/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config
 
### API
-  GET /login/oauth2/kakao/url
   - 로그인 버튼 클릭 시 Response 카카오 OAuth 인증 URL 반환 
    - response body : 
      - kakaoOAuthUrl : 카카오 로그인 시 인가코드를 받을 수 있는 URL
-  GET /login/oauth2/kakao/code
    - 로그인 처리 후 Response 객체를 통해 JWT 반환
    - headerValues: "Bearer " + jwtToken
    - response body : 
      - thumbnail : 회원의 프로필 사진 썸네일
      - registDate : 회원의 서비스 가입일
- GET /api/member-test-result/{kakaoId}
  - memberId를 기준으로 테스트 결과를 10개씩 반환
  - Path Parameters : 
    - kakaoId(필수): 조회하고자 하는 회원의 ID
  - Query Parameters : 
    - page (선택) : 페이지 번호. 기본 값은 0
    - size (선택) : 한 페이지당 보여줄 결과의 수. 기본 값은 10.
  - Headers :
    - Authorization(필수): "Bearer " + jwtToken
  - 실패시:
    - 401 Unauthorized : JWT 토큰이 유효하지 않는 경우, Response Body에는 "토큰이 유효하지 않습니다." 메시지 반환.

**Comment by jj123859** [comment]
### Test 검사 과정 API (예정) @Moorisong

*figma 화면 분할 제목 참조
- *C-1 test_main   

  - GET /detail/{test_id}

- *C-2 test_progress   

  - GET /t/{question_id}

- *C-3 test_result

  - GET /t/{question_id}/result/{result_id}

**Comment by HyeJi-An** [comment]
Test 등록(+수정, 삭제) 과정 API (예정) @Moorisong

- E-1 quiz_new
  - POST /quiz

- E-2 questions
  - POST /quiz/put/{question_id}

- E-3 results
  - POST /quiz/put/{test_id}/result/{result_id}

- E-4 update_questions
  - PATCH /quiz/update/{question_id}

- E-5 update_results
  - PATCH /quiz/update/{test_id}/result/{result_id}

- E-6 delete_quiz
  - @DELETE /quiz/delete/{test_id}

**Comment by jj123859** [comment]
- A-1 home
  - GET /quizzes
- B-1 test_list
  - GET /quizzes
